name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Example Step
        env:
          CONNECTION: ${{ secrets.CONNECTION }}
        run: |
          echo "Connection string: $CONNECTION"
          # Use the CONNECTION variable in your commands here
